### ISSUE TITLE
请问如何修改为适用于x64架构的链接器？

### ISSUE THREAD

**Issue by AprilWinds** [ksco/rvld#1]
是需要修改elf文件机器类型魔数和载入地址吗？

**Comment by ksco** [comment]
主要的工作是修改 input sections 中 relocation 的部分，这部分是架构相关的。

**Comment by AprilWinds** [comment]
> 主要的工作是修改 input sections 中 relocation 的部分，这部分是架构相关的。

谢谢您的答疑，请问有这方面的参考资料或代码吗？

**Comment by ksco** [comment]
可以看一下 mold 或者 LLVM lld 的代码。
