### ISSUE TITLE
chunk中shndx字段只有使用而从未定义

### ISSUE THREAD

**Issue by Bri1987** [ksco/rvld#5]
点击chunk中的shndx字段可显示chunk.go中的`GetShndx()`是这个字段的only usage，除此之外好像却并没有找到shndx被定义的地方（可能是我没有找到，如果是我的疏忽，则非常抱歉打扰）。`GetShndx()`方法在outputshdr.go中的`copyBuf`和`updateShdr`中总共被调用四次，用于判断是否chunk有对应的section header，比如：
```
if chunk.GetShndx() > 0 {
	utils.Write[Elf32_Shdr](base[chunk.GetShndx()*int64(ShdrSize):],
		*chunk.GetShdr())
}
```
因为shndx都未定义而是0，好像上述代码都是没有效果的。但是这样最终的hello world仍跑出来了，是因为目标文件本身就可以没有section header table，所以影响不大吗？

**Comment by ksco** [comment]
是的，执行过程中不需要 section header table。因为想尽可能地精简课程代码，所以就把这部分都删掉了，但没删干净。我在上面把这部分也删除了，感谢指出！
